### ISSUE TITLE
Using stata-autokey on vscode

### ISSUE THREAD

**Issue by josempascual** [kylebarron/stata-autokey#9]
Hi,

I was wondering how to set up this script for Visual Studio. Thank you!

**Comment by kylebarron** [comment]
Replace `Atom` with the name of the window you're typing in. Everything else should work.
https://github.com/kylebarron/stata-autokey/blob/fd9eed198e20e6e66e04bc5a080a88e7ff64fe12/code/run_stata_chunk.py#L8

**Comment by josempascual** [comment]
Sorry for the slow answer, with that small correction it works. Thank you!
